/**
 * Character Classes System for SoulBonker 3D
 * 9 Playable Classes: Chevalier, Archer, Mage, Space Marine, Ange, Voleur, Ork, Reaper, Nécromancien
 */

export const CHARACTER_CLASSES = {
  KNIGHT: {
    id: 'KNIGHT',
    name: 'Chevalier Bonkeur',
    title: 'Guerrier Souls-Like',
    icon: '🛡️',
    color: '#00f0ff',
    modelPath: 'assets/models/knight_torso.obj',
    mtlPath: 'assets/models/knight.mtl',
    isMultiPart: true,
    parts: {
      torso: { model: 'assets/models/knight_torso.obj', mtl: 'assets/models/knight.mtl' },
      armR: { model: 'assets/models/knight_arm_r.obj', mtl: 'assets/models/knight.mtl' },
      armL: { model: 'assets/models/knight_arm_l.obj', mtl: 'assets/models/knight.mtl' },
      legR: { model: 'assets/models/knight_leg_r.obj', mtl: 'assets/models/knight.mtl' },
      legL: { model: 'assets/models/knight_leg_l.obj', mtl: 'assets/models/knight.mtl' }
    },
    weaponModel: 'assets/models/warhammer.obj',
    weaponMtl: 'assets/models/warhammer.mtl',
    maxHp: 125,
    maxStamina: 105,
    moveSpeed: 10.2,
    baseDamage: 40,
    attackSpeed: 1.05,
    knockbackMultiplier: 1.15,
    isRanged: false,
    weaponType: 'WARHAMMER',
    heavyName: 'Grand Bonk Tellurique',
    dodgeType: 'ROLL',
    stats: {
      hp: '⭐⭐⭐⭐',
      speed: '⭐⭐⭐',
      damage: '⭐⭐⭐⭐',
      range: '⭐'
    },
    desc: 'Robuste et équilibré. Coups de massue colossale au corps-à-corps, esquives parfaites et Bullet Time.'
  },
  ARCHER: {
    id: 'ARCHER',
    name: 'Rôdeur Sylvestre',
    title: 'Tireur d\'Élite à l\'Arc',
    icon: '🏹',
    color: '#00ff88',
    modelPath: 'assets/models/archer.obj',
    mtlPath: 'assets/models/archer.mtl',
    weaponModel: 'assets/models/bow.obj',
    weaponMtl: 'assets/models/bow.mtl',
    maxHp: 85,
    maxStamina: 120,
    moveSpeed: 11.8,
    baseDamage: 28,
    attackSpeed: 1.4,
    knockbackMultiplier: 0.75,
    isRanged: true,
    weaponType: 'BOW',
    heavyName: 'Pluie de Flèches Perforantes',
    dodgeType: 'ACROBATIC_DASH',
    stats: {
      hp: '⭐⭐',
      speed: '⭐⭐⭐⭐⭐',
      damage: '⭐⭐⭐',
      range: '⭐⭐⭐⭐⭐'
    },
    desc: 'Ultra agile et rapide. Tire des flèches perçantes à distance pour faucher les ennemis avant qu\'ils n\'approchent.'
  },
  MAGE: {
    id: 'MAGE',
    name: 'Archimage Arcanique',
    title: 'Maître des Sorts',
    icon: '🧙',
    color: '#bb44ff',
    modelPath: 'assets/models/mage.obj',
    mtlPath: 'assets/models/mage.mtl',
    weaponModel: 'assets/models/staff.obj',
    weaponMtl: 'assets/models/staff.mtl',
    maxHp: 75,
    maxStamina: 110,
    moveSpeed: 9.5,
    baseDamage: 32,
    attackSpeed: 1.15,
    knockbackMultiplier: 0.9,
    isRanged: true,
    weaponType: 'STAFF',
    heavyName: 'Supernova Arcanique Éclatante',
    dodgeType: 'TELEPORT_BLINK',
    stats: {
      hp: '⭐',
      speed: '⭐⭐⭐',
      damage: '⭐⭐⭐⭐⭐',
      range: '⭐⭐⭐⭐'
    },
    desc: 'Lance des orbes arcaniques explosives à tête chercheuse. Se téléporte instantanément lors des esquives.'
  },
  SPACEMARINE: {
    id: 'SPACEMARINE',
    name: 'Black Templar',
    title: 'Space Marine de l\'Imperium',
    icon: '⚔️',
    color: '#ff3300',
    modelPath: 'assets/models/spacemarine.obj',
    mtlPath: 'assets/models/spacemarine.mtl',
    weaponModel: 'assets/models/chainsword.obj',
    weaponMtl: 'assets/models/chainsword.mtl',
    maxHp: 180,
    maxStamina: 80,
    moveSpeed: 8.8,
    baseDamage: 54,
    attackSpeed: 1.25,
    knockbackMultiplier: 1.6,
    isRanged: false,
    weaponType: 'CHAINSWORD',
    heavyName: 'Frappe Tronçonneuse & Bolter Explosif',
    dodgeType: 'POWER_STOMP',
    stats: {
      hp: '⭐⭐⭐⭐⭐',
      speed: '⭐⭐',
      damage: '⭐⭐⭐⭐⭐',
      range: '⭐⭐'
    },
    desc: 'Pour l\'Empereur ! Armure énergétique ultra-lourde, épée-tronçonneuse dévastatrice et tirs de Bolter destructeurs.'
  },
  ANGEL: {
    id: 'ANGEL',
    name: 'Ange Céleste',
    title: 'Paladin de Pure Lumière',
    icon: '👼',
    color: '#ffd700',
    modelPath: 'assets/models/angel_torso.obj',
    mtlPath: 'assets/models/angel.mtl',
    isMultiPart: true,
    parts: {
      torso: { model: 'assets/models/angel_torso.obj', mtl: 'assets/models/angel.mtl' },
      armR: { model: 'assets/models/angel_arm_r.obj', mtl: 'assets/models/angel.mtl' },
      armL: { model: 'assets/models/angel_arm_l.obj', mtl: 'assets/models/angel.mtl' },
      legR: { model: 'assets/models/angel_leg_r.obj', mtl: 'assets/models/angel.mtl' },
      legL: { model: 'assets/models/angel_leg_l.obj', mtl: 'assets/models/angel.mtl' }
    },
    weaponModel: 'assets/models/angel_sword.obj',
    weaponMtl: 'assets/models/angel_sword.mtl',
    maxHp: 130,
    maxStamina: 115,
    moveSpeed: 10.6,
    baseDamage: 42,
    attackSpeed: 1.2,
    knockbackMultiplier: 1.2,
    isRanged: false,
    weaponType: 'ANGEL_SWORD',
    heavyName: 'Châtiment Solaire Divin',
    dodgeType: 'WINGS_GLIDE',
    stats: {
      hp: '⭐⭐⭐⭐',
      speed: '⭐⭐⭐⭐',
      damage: '⭐⭐⭐⭐',
      range: '⭐⭐'
    },
    desc: 'Archange divin. Ailes dorées lumineuses, frappes saintes éblouissantes et rayon de châtiment céleste.'
  },
  ROGUE: {
    id: 'ROGUE',
    name: 'Voleur de l\'Ombre',
    title: 'Assassin Fantôme',
    icon: '🗡️',
    color: '#e0aaff',
    modelPath: 'assets/models/rogue.obj',
    mtlPath: 'assets/models/rogue.mtl',
    weaponModel: 'assets/models/dagger.obj',
    weaponMtl: 'assets/models/dagger.mtl',
    maxHp: 80,
    maxStamina: 140,
    moveSpeed: 12.8,
    baseDamage: 30,
    attackSpeed: 1.85,
    knockbackMultiplier: 0.6,
    isRanged: false,
    weaponType: 'DAGGER',
    heavyName: 'Danse des Lames & Coup Critique (3x)',
    dodgeType: 'SMOKE_STEP',
    stats: {
      hp: '⭐⭐',
      speed: '⭐⭐⭐⭐⭐',
      damage: '⭐⭐⭐⭐',
      range: '⭐'
    },
    desc: 'Le plus rapide des héros ! Double dague d\'ombre, enchaînements supersoniques et coups critiques dévastateurs.'
  },
  ORK: {
    id: 'ORK',
    name: 'Ork Berserker',
    title: 'Seigneur WAAAAGH !',
    icon: '🧌',
    color: '#44bb22',
    modelPath: 'assets/models/ork.obj',
    mtlPath: 'assets/models/ork.mtl',
    weaponModel: 'assets/models/ork_choppa.obj',
    weaponMtl: 'assets/models/ork_choppa.mtl',
    maxHp: 210,
    maxStamina: 75,
    moveSpeed: 8.5,
    baseDamage: 62,
    attackSpeed: 0.95,
    knockbackMultiplier: 2.2,
    isRanged: false,
    weaponType: 'CHOPPA',
    heavyName: 'WAAAAGH ! Écrasement Brutal',
    dodgeType: 'BULL_CHARGE',
    stats: {
      hp: '⭐⭐⭐⭐⭐',
      speed: '⭐',
      damage: '⭐⭐⭐⭐⭐',
      range: '⭐'
    },
    desc: 'Colosse de guerre ork. Le plus grand réservoir de PV du jeu et dégâts terrifiants avec son Kikoup\' géant.'
  },
  REAPER: {
    id: 'REAPER',
    name: 'Faucheur Spectral',
    title: 'Moissonneur d\'Âmes',
    icon: '💀',
    color: '#00e5ff',
    modelPath: 'assets/models/reaper.obj',
    mtlPath: 'assets/models/reaper.mtl',
    weaponModel: null, // Scythe is sculpted directly in the 3D model
    weaponMtl: null,
    maxHp: 95,
    maxStamina: 105,
    moveSpeed: 10.2,
    baseDamage: 46,
    attackSpeed: 1.1,
    knockbackMultiplier: 1.1,
    isRanged: false,
    hasIntegratedWeapon: true,
    weaponType: 'INTEGRATED_SCYTHE',
    heavyName: 'Tourbillon Moissonneur (Vol de Vie)',
    dodgeType: 'SPECTRAL_PHASE',
    stats: {
      hp: '⭐⭐⭐',
      speed: '⭐⭐⭐',
      damage: '⭐⭐⭐⭐⭐',
      range: '⭐⭐⭐'
    },
    desc: 'Incarnation de la mort. Grande Faux spectrale fauchant à 360° et absorbant la vie des ennemis touchés.'
  },
  NECROMANCER: {
    id: 'NECROMANCER',
    name: 'Nécromancien',
    title: 'Invocateur des Morts',
    icon: '🧟',
    color: '#00ff66',
    modelPath: 'assets/models/necromancer.obj',
    mtlPath: 'assets/models/necromancer.mtl',
    weaponModel: null,
    weaponMtl: null,
    maxHp: 90,
    maxStamina: 100,
    moveSpeed: 9.8,
    baseDamage: 32,
    attackSpeed: 1.2,
    knockbackMultiplier: 0.85,
    isRanged: true,
    weaponType: 'NECRO_STAFF',
    heavyName: 'Invoque 3 Guerriers Squelettes',
    dodgeType: 'BONE_DISSOLVE',
    stats: {
      hp: '⭐⭐',
      speed: '⭐⭐⭐',
      damage: '⭐⭐⭐⭐',
      range: '⭐⭐⭐⭐⭐'
    },
    desc: 'Tire des crânes d\'âmes vertes et invoque jusqu\'à 3 serviteurs Squelettes guerriers qui attaquent pour lui !'
  }
};
