[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=84E8F23149A045B88D6F63991209B19C
ProjectName=SoulBonker 3D
ProjectVersion=1.0.0.0

[/Script/Engine.RendererSettings]
; === OPTIMISATIONS BASSE MÉMOIRE MACBOOK (ANTI-CRASH RAM) ===
r.Lumen.DiffuseIndirect.Allow=0
r.Lumen.Reflections.Allow=0
r.Nanite.ProjectEnabled=0
r.Shadow.Virtual.Enable=0
r.RayTracing=0
r.VolumetricCloud=0
r.AmbientOcclusionLevels=0
r.DistanceFields=0
r.MeshCardRepresentation=0
r.SkinCache.CompileShaders=0

; Limiter les processus de compilation de shaders pour ne pas saturer la RAM
r.ShaderCompiler.WorkerThreads=2
r.ShaderCompiler.MaxShaderJobsPerProcess=16

[/Script/MacTargetPlatform.MacTargetSettings]
TargetedRHIs=SF_METAL
bUseMetalCRT=False
